//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DailyClassView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DailyClassView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("centrny.Resources.DailyClassView", typeof(DailyClassView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Class.
        /// </summary>
        public static string AddClassBtn {
            get {
                return ResourceManager.GetString("AddClassBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Classes.
        /// </summary>
        public static string CalendarDayHeader {
            get {
                return ResourceManager.GetString("CalendarDayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string CapacityLabel {
            get {
                return ResourceManager.GetString("CapacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ClassDetailsModalClose {
            get {
                return ResourceManager.GetString("ClassDetailsModalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ClassDetailsModalDeleteBtn {
            get {
                return ResourceManager.GetString("ClassDetailsModalDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ClassDetailsModalEditBtn {
            get {
                return ResourceManager.GetString("ClassDetailsModalEditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Details.
        /// </summary>
        public static string ClassDetailsModalTitle {
            get {
                return ResourceManager.GetString("ClassDetailsModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string CostLabel {
            get {
                return ResourceManager.GetString("CostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating class: .
        /// </summary>
        public static string CreateError {
            get {
                return ResourceManager.GetString("CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Day.
        /// </summary>
        public static string DateNavNext {
            get {
                return ResourceManager.GetString("DateNavNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Day.
        /// </summary>
        public static string DateNavPrev {
            get {
                return ResourceManager.GetString("DateNavPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be after start time.
        /// </summary>
        public static string EndTimeError {
            get {
                return ResourceManager.GetString("EndTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorBanner {
            get {
                return ResourceManager.GetString("ErrorBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading branch.
        /// </summary>
        public static string ErrorLoadingBranch {
            get {
                return ResourceManager.GetString("ErrorLoadingBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Class.
        /// </summary>
        public static string FloatingAddBtnTitle {
            get {
                return ResourceManager.GetString("FloatingAddBtnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string FormBranch {
            get {
                return ResourceManager.GetString("FormBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormCancel {
            get {
                return ResourceManager.GetString("FormCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string FormCenter {
            get {
                return ResourceManager.GetString("FormCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Amount.
        /// </summary>
        public static string FormCenterAmount {
            get {
                return ResourceManager.GetString("FormCenterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string FormClassName {
            get {
                return ResourceManager.GetString("FormClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Price.
        /// </summary>
        public static string FormClassPrice {
            get {
                return ResourceManager.GetString("FormClassPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Year.
        /// </summary>
        public static string FormEduYear {
            get {
                return ResourceManager.GetString("FormEduYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string FormEndTime {
            get {
                return ResourceManager.GetString("FormEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        public static string FormHall {
            get {
                return ResourceManager.GetString("FormHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        public static string FormLesson {
            get {
                return ResourceManager.GetString("FormLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Students.
        /// </summary>
        public static string FormNoOfStudents {
            get {
                return ResourceManager.GetString("FormNoOfStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Class.
        /// </summary>
        public static string FormSaveClass {
            get {
                return ResourceManager.GetString("FormSaveClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string FormStartTime {
            get {
                return ResourceManager.GetString("FormStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string FormSubject {
            get {
                return ResourceManager.GetString("FormSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string FormTeacher {
            get {
                return ResourceManager.GetString("FormTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Amount.
        /// </summary>
        public static string FormTeacherAmount {
            get {
                return ResourceManager.GetString("FormTeacherAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string FormTotalAmount {
            get {
                return ResourceManager.GetString("FormTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string FormYear {
            get {
                return ResourceManager.GetString("FormYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string ForUser {
            get {
                return ResourceManager.GetString("ForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Weekly Classes.
        /// </summary>
        public static string GenerateWeeklyBtn {
            get {
                return ResourceManager.GetString("GenerateWeeklyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center User.
        /// </summary>
        public static string IsCenterLabel {
            get {
                return ResourceManager.GetString("IsCenterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher User.
        /// </summary>
        public static string IsTeacherLabel {
            get {
                return ResourceManager.GetString("IsTeacherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string LegendClasses {
            get {
                return ResourceManager.GetString("LegendClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct classes (Added from daily view).
        /// </summary>
        public static string LegendDirect {
            get {
                return ResourceManager.GetString("LegendDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation-based (Specific date).
        /// </summary>
        public static string LegendReservation {
            get {
                return ResourceManager.GetString("LegendReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule-based (Recurring).
        /// </summary>
        public static string LegendSchedule {
            get {
                return ResourceManager.GetString("LegendSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error occurred: .
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No classes scheduled.
        /// </summary>
        public static string NoClassesScheduled {
            get {
                return ResourceManager.GetString("NoClassesScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Add New Class&quot; to schedule your first class for this day..
        /// </summary>
        public static string NoClassesSubText {
            get {
                return ResourceManager.GetString("NoClassesSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your classes for each day - Calendar View.
        /// </summary>
        public static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshBtn {
            get {
                return ResourceManager.GetString("RefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Code.
        /// </summary>
        public static string RootCodeLabel {
            get {
                return ResourceManager.GetString("RootCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save class. Please contact administrator..
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class created successfully!.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lesson.
        /// </summary>
        public static string SelectLesson {
            get {
                return ResourceManager.GetString("SelectLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Classes.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayBtn {
            get {
                return ResourceManager.GetString("TodayBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating class: .
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class updated successfully!.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily classes for:.
        /// </summary>
        public static string UserContextBanner {
            get {
                return ResourceManager.GetString("UserContextBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view and manage classes for your assigned organization only.
        /// </summary>
        public static string UserContextBannerSub {
            get {
                return ResourceManager.GetString("UserContextBannerSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking status....
        /// </summary>
        public static string WeeklyGenerationBannerChecking {
            get {
                return ResourceManager.GetString("WeeklyGenerationBannerChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate This Week.
        /// </summary>
        public static string WeeklyGenerationBannerGenerateBtn {
            get {
                return ResourceManager.GetString("WeeklyGenerationBannerGenerateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Class Generation.
        /// </summary>
        public static string WeeklyGenerationBannerTitle {
            get {
                return ResourceManager.GetString("WeeklyGenerationBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string WeeklyGenerationBannerViewBtn {
            get {
                return ResourceManager.GetString("WeeklyGenerationBannerViewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WeeklyGenerationModalClose {
            get {
                return ResourceManager.GetString("WeeklyGenerationModalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Classes.
        /// </summary>
        public static string WeeklyGenerationModalGenerateBtn {
            get {
                return ResourceManager.GetString("WeeklyGenerationModalGenerateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading generation status....
        /// </summary>
        public static string WeeklyGenerationModalLoading {
            get {
                return ResourceManager.GetString("WeeklyGenerationModalLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Class Generation Status.
        /// </summary>
        public static string WeeklyGenerationModalTitle {
            get {
                return ResourceManager.GetString("WeeklyGenerationModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Schedules.
        /// </summary>
        public static string WeeklySchedulesBtn {
            get {
                return ResourceManager.GetString("WeeklySchedulesBtn", resourceCulture);
            }
        }
    }
}
