//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EduYearView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EduYearView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("centrny.Resources.EduYearView", typeof(EduYearView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Edu Year.
        /// </summary>
        public static string AddEduYear {
            get {
                return ResourceManager.GetString("AddEduYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Level.
        /// </summary>
        public static string AddLevel {
            get {
                return ResourceManager.GetString("AddLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Year.
        /// </summary>
        public static string AddYear {
            get {
                return ResourceManager.GetString("AddYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edu Year Code.
        /// </summary>
        public static string EduYearCode {
            get {
                return ResourceManager.GetString("EduYearCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edu Year Name.
        /// </summary>
        public static string EduYearName {
            get {
                return ResourceManager.GetString("EduYearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Years List.
        /// </summary>
        public static string EduYearsList {
            get {
                return ResourceManager.GetString("EduYearsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Name.
        /// </summary>
        public static string LevelName {
            get {
                return ResourceManager.GetString("LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active Educational Year found. Please activate an Edu Year first..
        /// </summary>
        public static string NoActiveEduYear {
            get {
                return ResourceManager.GetString("NoActiveEduYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No levels found for this root..
        /// </summary>
        public static string NoLevelsFound {
            get {
                return ResourceManager.GetString("NoLevelsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No years found for this level.
        /// </summary>
        public static string NoYearsFound {
            get {
                return ResourceManager.GetString("NoYearsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Code.
        /// </summary>
        public static string YearCode {
            get {
                return ResourceManager.GetString("YearCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Name.
        /// </summary>
        public static string YearName {
            get {
                return ResourceManager.GetString("YearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string YearsForActiveEduYear {
            get {
                return ResourceManager.GetString("YearsForActiveEduYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string YearSort {
            get {
                return ResourceManager.GetString("YearSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
