//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centrny.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("centrny.Resources.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Employee_Actions {
            get {
                return ResourceManager.GetString("Employee_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Employee_Active {
            get {
                return ResourceManager.GetString("Employee_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string Employee_AddBtn {
            get {
                return ResourceManager.GetString("Employee_AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Employee.
        /// </summary>
        public static string Employee_AddEditModalTitle {
            get {
                return ResourceManager.GetString("Employee_AddEditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string Employee_AddModalTitle {
            get {
                return ResourceManager.GetString("Employee_AddModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Employee_BranchLabel {
            get {
                return ResourceManager.GetString("Employee_BranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Employee_Cancel {
            get {
                return ResourceManager.GetString("Employee_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add employee..
        /// </summary>
        public static string Employee_CouldNotAdd {
            get {
                return ResourceManager.GetString("Employee_CouldNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete employee..
        /// </summary>
        public static string Employee_CouldNotDelete {
            get {
                return ResourceManager.GetString("Employee_CouldNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not edit employee..
        /// </summary>
        public static string Employee_CouldNotEdit {
            get {
                return ResourceManager.GetString("Employee_CouldNotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Employee_DeleteBtn {
            get {
                return ResourceManager.GetString("Employee_DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this employee?.
        /// </summary>
        public static string Employee_DeleteConfirm {
            get {
                return ResourceManager.GetString("Employee_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee.
        /// </summary>
        public static string Employee_EditModalTitle {
            get {
                return ResourceManager.GetString("Employee_EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Employee_EmailLabel {
            get {
                return ResourceManager.GetString("Employee_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data..
        /// </summary>
        public static string Employee_ErrorLoading {
            get {
                return ResourceManager.GetString("Employee_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Employee_Inactive {
            get {
                return ResourceManager.GetString("Employee_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Employee_IsActiveLabel {
            get {
                return ResourceManager.GetString("Employee_IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employee_ListTitle {
            get {
                return ResourceManager.GetString("Employee_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Employee_NameLabel {
            get {
                return ResourceManager.GetString("Employee_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employees found..
        /// </summary>
        public static string Employee_NoEmployees {
            get {
                return ResourceManager.GetString("Employee_NoEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        public static string Employee_NotFound {
            get {
                return ResourceManager.GetString("Employee_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Employee_PhoneLabel {
            get {
                return ResourceManager.GetString("Employee_PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields..
        /// </summary>
        public static string Employee_PleaseFillFields {
            get {
                return ResourceManager.GetString("Employee_PleaseFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Employee_Processing {
            get {
                return ResourceManager.GetString("Employee_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Employee_SalaryLabel {
            get {
                return ResourceManager.GetString("Employee_SalaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Employee_Save {
            get {
                return ResourceManager.GetString("Employee_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select Branch --.
        /// </summary>
        public static string Employee_SelectBranch {
            get {
                return ResourceManager.GetString("Employee_SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select User --.
        /// </summary>
        public static string Employee_SelectUser {
            get {
                return ResourceManager.GetString("Employee_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Employee_StartDateLabel {
            get {
                return ResourceManager.GetString("Employee_StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string Employee_Unauthorized {
            get {
                return ResourceManager.GetString("Employee_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Employee_UserLabel {
            get {
                return ResourceManager.GetString("Employee_UserLabel", resourceCulture);
            }
        }
    }
}
