//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centrny.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("centrny.Resources.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Management System.
        /// </summary>
        public static string Login_CenterManagementSystem {
            get {
                return ResourceManager.GetString("Login_CenterManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Login_Close {
            get {
                return ResourceManager.GetString("Login_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Test Credentials:.
        /// </summary>
        public static string Login_CommonTestCredentials {
            get {
                return ResourceManager.GetString("Login_CommonTestCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Your Username.
        /// </summary>
        public static string Login_FindUsername {
            get {
                return ResourceManager.GetString("Login_FindUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Password.
        /// </summary>
        public static string Login_HidePassword {
            get {
                return ResourceManager.GetString("Login_HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 3 characters.
        /// </summary>
        public static string Login_PasswordMinLength {
            get {
                return ResourceManager.GetString("Login_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Login_PasswordRequired {
            get {
                return ResourceManager.GetString("Login_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Password.
        /// </summary>
        public static string Login_PasswordToggle {
            get {
                return ResourceManager.GetString("Login_PasswordToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me signed in for 8 hours.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this SQL query in your database:.
        /// </summary>
        public static string Login_RunSqlQuery {
            get {
                return ResourceManager.GetString("Login_RunSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string Login_ShowPassword {
            get {
                return ResourceManager.GetString("Login_ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing In....
        /// </summary>
        public static string Login_SigningIn {
            get {
                return ResourceManager.GetString("Login_SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Check if users exist.
        /// </summary>
        public static string Login_Step1 {
            get {
                return ResourceManager.GetString("Login_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Verify password hashes.
        /// </summary>
        public static string Login_Step2 {
            get {
                return ResourceManager.GetString("Login_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Create a test user.
        /// </summary>
        public static string Login_Step3 {
            get {
                return ResourceManager.GetString("Login_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl+D to find your username • Check database for actual user records.
        /// </summary>
        public static string Login_TroubleshootingHint {
            get {
                return ResourceManager.GetString("Login_TroubleshootingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting Login Issues.
        /// </summary>
        public static string Login_TroubleshootingLink {
            get {
                return ResourceManager.GetString("Login_TroubleshootingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Password should automatically hash to MD5. If Group_Code 1 doesn&apos;t exist, create a group first or use an existing Group_Code from your database..
        /// </summary>
        public static string Login_TroubleshootingNote {
            get {
                return ResourceManager.GetString("Login_TroubleshootingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting Steps.
        /// </summary>
        public static string Login_TroubleshootingSteps {
            get {
                return ResourceManager.GetString("Login_TroubleshootingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting Login Issues.
        /// </summary>
        public static string Login_TroubleshootingTitle {
            get {
                return ResourceManager.GetString("Login_TroubleshootingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 3 characters.
        /// </summary>
        public static string Login_UsernameMinLength {
            get {
                return ResourceManager.GetString("Login_UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain letters, numbers, and underscores.
        /// </summary>
        public static string Login_UsernamePattern {
            get {
                return ResourceManager.GetString("Login_UsernamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        public static string Login_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Login_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string Login_UsernameRequired {
            get {
                return ResourceManager.GetString("Login_UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string Login_WelcomeBack {
            get {
                return ResourceManager.GetString("Login_WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Title_Login {
            get {
                return ResourceManager.GetString("Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Center Management System.
        /// </summary>
        public static string Title_LoginPage {
            get {
                return ResourceManager.GetString("Title_LoginPage", resourceCulture);
            }
        }
    }
}
