//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace centrny.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Subject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subject() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("centrny.Resources.Subject", typeof(Subject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Subject_Actions {
            get {
                return ResourceManager.GetString("Subject_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subject.
        /// </summary>
        public static string Subject_AddBtn {
            get {
                return ResourceManager.GetString("Subject_AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subject.
        /// </summary>
        public static string Subject_AddModalTitle {
            get {
                return ResourceManager.GetString("Subject_AddModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Teacher.
        /// </summary>
        public static string Subject_AddTeacher {
            get {
                return ResourceManager.GetString("Subject_AddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Teacher.
        /// </summary>
        public static string Subject_AssignTeacher {
            get {
                return ResourceManager.GetString("Subject_AssignTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Teacher to Subject.
        /// </summary>
        public static string Subject_AssignTeacherToSubjectTitle {
            get {
                return ResourceManager.GetString("Subject_AssignTeacherToSubjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Subject_BranchLabel {
            get {
                return ResourceManager.GetString("Subject_BranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch not found..
        /// </summary>
        public static string Subject_BranchNotFound {
            get {
                return ResourceManager.GetString("Subject_BranchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Amount.
        /// </summary>
        public static string Subject_CenterAmountLabel {
            get {
                return ResourceManager.GetString("Subject_CenterAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Percentage.
        /// </summary>
        public static string Subject_CenterPercentageLabel {
            get {
                return ResourceManager.GetString("Subject_CenterPercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Subject_Close {
            get {
                return ResourceManager.GetString("Subject_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add subject.
        /// </summary>
        public static string Subject_CouldNotAdd {
            get {
                return ResourceManager.GetString("Subject_CouldNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not assign teacher.
        /// </summary>
        public static string Subject_CouldNotAssignTeacher {
            get {
                return ResourceManager.GetString("Subject_CouldNotAssignTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not assign teacher: {0}.
        /// </summary>
        public static string Subject_CouldNotAssignTeacher_Server {
            get {
                return ResourceManager.GetString("Subject_CouldNotAssignTeacher_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete subject.
        /// </summary>
        public static string Subject_CouldNotDelete {
            get {
                return ResourceManager.GetString("Subject_CouldNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine EduYearCode for the selected year..
        /// </summary>
        public static string Subject_CouldNotDetermineEduYear {
            get {
                return ResourceManager.GetString("Subject_CouldNotDetermineEduYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not edit subject.
        /// </summary>
        public static string Subject_CouldNotEdit {
            get {
                return ResourceManager.GetString("Subject_CouldNotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this subject?.
        /// </summary>
        public static string Subject_DeleteConfirm {
            get {
                return ResourceManager.GetString("Subject_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Subject.
        /// </summary>
        public static string Subject_EditBtn {
            get {
                return ResourceManager.GetString("Subject_EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Subject.
        /// </summary>
        public static string Subject_EditModalTitle {
            get {
                return ResourceManager.GetString("Subject_EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred loading subjects..
        /// </summary>
        public static string Subject_ErrorLoading {
            get {
                return ResourceManager.GetString("Subject_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading years.
        /// </summary>
        public static string Subject_ErrorLoadingYears {
            get {
                return ResourceManager.GetString("Subject_ErrorLoadingYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data..
        /// </summary>
        public static string Subject_InvalidData {
            get {
                return ResourceManager.GetString("Subject_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Primary.
        /// </summary>
        public static string Subject_IsPrimary {
            get {
                return ResourceManager.GetString("Subject_IsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Primary?.
        /// </summary>
        public static string Subject_IsPrimaryLabel {
            get {
                return ResourceManager.GetString("Subject_IsPrimaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects List.
        /// </summary>
        public static string Subject_ListTitle {
            get {
                return ResourceManager.GetString("Subject_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Subject_LoadingYears {
            get {
                return ResourceManager.GetString("Subject_LoadingYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name.
        /// </summary>
        public static string Subject_NameLabel {
            get {
                return ResourceManager.GetString("Subject_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Subject_No {
            get {
                return ResourceManager.GetString("Subject_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active years.
        /// </summary>
        public static string Subject_NoActiveYears {
            get {
                return ResourceManager.GetString("Subject_NoActiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subjects found for your group..
        /// </summary>
        public static string Subject_NoSubjects {
            get {
                return ResourceManager.GetString("Subject_NoSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No teachers assigned..
        /// </summary>
        public static string Subject_NoTeachersAssigned {
            get {
                return ResourceManager.GetString("Subject_NoTeachersAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your group or root was not found..
        /// </summary>
        public static string Subject_NotFound {
            get {
                return ResourceManager.GetString("Subject_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields..
        /// </summary>
        public static string Subject_PleaseFillFields {
            get {
                return ResourceManager.GetString("Subject_PleaseFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Subject_Processing {
            get {
                return ResourceManager.GetString("Subject_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Teachers.
        /// </summary>
        public static string Subject_ShowTeachers {
            get {
                return ResourceManager.GetString("Subject_ShowTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject not found..
        /// </summary>
        public static string Subject_SubjectNotFound {
            get {
                return ResourceManager.GetString("Subject_SubjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Subject_Submit {
            get {
                return ResourceManager.GetString("Subject_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher assigned to subject successfully..
        /// </summary>
        public static string Subject_SuccessTeacherAssigned {
            get {
                return ResourceManager.GetString("Subject_SuccessTeacherAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string Subject_TeacherLabel {
            get {
                return ResourceManager.GetString("Subject_TeacherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher not found..
        /// </summary>
        public static string Subject_TeacherNotFound {
            get {
                return ResourceManager.GetString("Subject_TeacherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized. Please log in..
        /// </summary>
        public static string Subject_Unauthorized {
            get {
                return ResourceManager.GetString("Subject_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Subject_YearLabel {
            get {
                return ResourceManager.GetString("Subject_YearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Name.
        /// </summary>
        public static string Subject_YearName {
            get {
                return ResourceManager.GetString("Subject_YearName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Subject_Yes {
            get {
                return ResourceManager.GetString("Subject_Yes", resourceCulture);
            }
        }
    }
}
